### ISSUE TITLE
Add GitHub CI

### ISSUE THREAD

**Issue by QubitPi** [paion-data/screwdriver#4]
> [!TIP]
> 
> **Thank you for contributing!** We would like to give our warmest welcome and appreciation on your contributions to our project. 😃 
>
> Contributing to open source project is an excellent way to
>
> 1. build up your resume with real industry experience, which recruiters consider highly valuable 🥇  
> 2. learn how to build "real-life" softwares and the industry's best technology standards 🚀  
> 3. "shortcut" interview process if your are interested in joining us and working in our company 🤝 

Goal
----

Enable project CI so that each pull request will trigger the test

Steps
-----

1. [Fork](https://github.com/paion-data/screwdriver/fork) or clone the repository
2. Create a new branch with `git checkout -b <branch name>`
3. Create a new directory called `.github` in the project root
4. Create a new directory called `workflows` under `./github` directory
5. Create a [GitHub Action](https://github.com/features/actions) file named **ci-cd.yml** under `workflow` directory with the following contents:

    ```yaml
    # Copyright Jiaqi Liu. All rights reserved.
    ---
    name: Screwdriver API CI/CD
    
    "on":
        pull_request:
        push:
            branches:
                - master
    
    jobs:
        tests:
            name: Unit Tests
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v3
                - name: Set node version to 18
                  uses: actions/setup-node@v3
                  with:
                      node-version: 18
                - name: Install dependencies
                  run: npm install
                - name: Run unit tests
                  run: npm test
    ```

6. Add CI/CD badge to README by appending the following lines at the end of [README.md](https://github.com/paion-data/screwdriver/blob/master/README.md): 

   ```
   [GitHub Workflow Status]: https://img.shields.io/github/actions/workflow/status/paion-data/screwdriver/ci-cd.yml?branch=master&logo=github&style=for-the-badge
   ```

   then display the badge by adding the following two lines above the original badge lines

   ```
   [![GitHub Workflow Status][GitHub Workflow Status]](https://github.com/paion-data/screwdriver/actions/workflows/ci-cd.yml)
   ![Last Commit](https://img.shields.io/github/last-commit/paion-data/screwdriver/master?logo=github&style=for-the-badge)
   ```

7. [Create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Our team will be notified automatically and start reviewing your pull request as soon as possible.
