### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by QubitPi** [paion-data/screwdriver#5]
> [!TIP]
> 
> **Thank you for contributing!** We would like to give our warmest welcome and appreciation on your contributions to our project. 😃 
>
> Contributing to open source project is an excellent way to
>
> 1. build up your resume with real industry experience, which recruiters consider highly valuable 🥇  
> 2. learn how to build "real-life" softwares and the industry's best technology standards 🚀  
> 3. "shortcut" interview process if your are interested in joining us and working in our company 🤝 

Goal
----

Publish Screwdriver API server docker images to Docker Hub so it can be deployed for the team

Steps
-----

> [!IMPORTANT]
> This issue has a prerequisite of https://github.com/paion-data/screwdriver/issues/4. Make sure https://github.com/paion-data/screwdriver/issues/4 is done before working on this issue

1. [Fork](https://github.com/paion-data/screwdriver/fork) or clone the repository
2. Create a new branch with `git checkout -b <branch name>`
3. Append the following [GitHub Action](https://github.com/features/actions) job definition at the end of `.github/workflows/ci-cd.yml` file:

    ```yaml
        docker-image:
            name: Build Test & Release Docker Image
            needs: tests
            runs-on: ubuntu-latest
            steps:
                - name: Checkout
                  uses: actions/checkout@v3
                - name: Set up QEMU
                  uses: docker/setup-qemu-action@v2
                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2
                - name: Test image build
                  uses: docker/build-push-action@v3
                  with:
                      context: .
                      push: false
                - name: Login to DockerHub
                  if: github.ref == 'refs/heads/master'
                  uses: docker/login-action@v2
                  with:
                      username: ${{ secrets.DOCKERHUB_USERNAME }}
                      password: ${{ secrets.DOCKERHUB_TOKEN }}
                - name: Push image to DockerHub
                  if: github.ref == 'refs/heads/master'
                  uses: docker/build-push-action@v3
                  with:
                      context: .
                      push: true
                      tags: ${{ secrets.DOCKERHUB_USERNAME }}/screwdriver:latest
                - name: Docker Hub Description
                  if: github.ref == 'refs/heads/master'
                  uses: peter-evans/dockerhub-description@v3
                  with:
                      username: ${{ secrets.DOCKERHUB_USERNAME }}
                      password: ${{ secrets.DOCKERHUB_TOKEN }}
                      repository: ${{ secrets.DOCKERHUB_USERNAME }}/screwdriver
    ```

4. [Create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Our team will be notified automatically and start reviewing your pull request as soon as possible.
