### ISSUE TITLE
Publish NPM package

### ISSUE THREAD

**Issue by QubitPi** [paion-data/screwdriver#6]
> [!TIP]
> 
> **Thank you for contributing!** We would like to give our warmest welcome and appreciation on your contributions to our project. 😃 
>
> Contributing to open source project is an excellent way to
>
> 1. build up your resume with real industry experience, which recruiters consider highly valuable 🥇  
> 2. learn how to build "real-life" softwares and the industry's best technology standards 🚀  
> 3. "shortcut" interview process if your are interested in joining us and working in our company 🤝 

Goal
----

This is a follow up of https://github.com/paion-data/screwdriver/issues/5. Docker image actually `npm install` the screwdriver package from NPM registry during image build, so NPM package should also be published in order to deploy our own customized SD API server.

Steps
-----

> [!IMPORTANT]
> This issue has a prerequisite of https://github.com/paion-data/screwdriver/issues/5. Make sure https://github.com/paion-data/screwdriver/issues/5 is done before working on this issue

1. [Fork](https://github.com/paion-data/screwdriver/fork) or clone the repository
2. Create a new branch with `git checkout -b <branch name>`
3. Split the `docker-image` job definition to 3 inter-dependent jobs

    ```yaml
        docker-test:
            name: Test Docker Image Build
            runs-on: ubuntu-latest
            steps:
                - name: Checkout
                  uses: actions/checkout@v3
                - name: Set up QEMU
                  uses: docker/setup-qemu-action@v2
                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2
                - name: Test image build
                  uses: docker/build-push-action@v3
                  with:
                      context: .
                      push: false
    
        release:
            name: Publish NPM Packages
            if: github.ref == 'refs/heads/master'
            needs: [tests, docker-test]
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v3
                  with:
                      fetch-depth: 0 # this is needed for feching tags for "tag-for-release.bash" below
                - name: Set node version to 18
                  uses: actions/setup-node@v3
                  with:
                      node-version: 18
                      registry-url: "https://registry.npmjs.org"
                - name: Download auto-version bump scripts
                  run: |
                      git clone https://github.com/QubitPi/hashicorp-aws.git ../hashicorp-aws
                      cp ../hashicorp-aws/.github/tag-for-release.bash .github/
                      cp ../hashicorp-aws/.github/upversion.py .github/
                - name: Tag for release
                  run: |
                      git config --global user.name '$USER'
                      git config --global user.email '$EMAIL'
                      .github/tag-for-release.bash
                - name: Set release version
                  run: |
                      VERSION=$(git describe)
                      npm version $VERSION
                - name: Publish to NPM Packages
                  run: |
                      npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
                      npm publish --access public
                  env:
                      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
        docker-image:
            name: Release Docker Image
            if: github.ref == 'refs/heads/master'
            needs: release
            runs-on: ubuntu-latest
            steps:
                - name: Checkout
                  uses: actions/checkout@v3
                - name: Set up QEMU
                  uses: docker/setup-qemu-action@v2
                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2
                - name: Login to DockerHub
                  uses: docker/login-action@v2
                  with:
                      username: ${{ secrets.DOCKERHUB_USERNAME }}
                      password: ${{ secrets.DOCKERHUB_TOKEN }}
                - name: Push image to DockerHub
                  uses: docker/build-push-action@v3
                  with:
                      context: .
                      push: true
                      tags: ${{ secrets.DOCKERHUB_USERNAME }}/screwdriver:latest
                - name: Docker Hub Description
                  uses: peter-evans/dockerhub-description@v3
                  with:
                      username: ${{ secrets.DOCKERHUB_USERNAME }}
                      password: ${{ secrets.DOCKERHUB_TOKEN }}
                      repository: ${{ secrets.DOCKERHUB_USERNAME }}/screwdriver
    
    ```

4. [Create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Our team will be notified automatically and start reviewing your pull request as soon as possible.
